# Język Python - Wykład 9

## Wydaje obliczenia numeryczne

Tworzenie tablic

In [1]:
def matrix(rows, cols):
    return [[0. for col in range(cols)] for row in range(rows)]

In [2]:
A = matrix(10, 10)
from pprint import pprint
print(A)

[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]


In [4]:
import numpy as np
B = np.zeros((10, 10))
print(B)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [8]:
C = np.array(A)
print(C)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [9]:
D = np.array([[1., 2.], [4., 5.], [6., 7.]])
print(D)

[[ 1.  2.]
 [ 4.  5.]
 [ 6.  7.]]


In [10]:
print(D[0, 0])
print(D[2, 1])

1.0
7.0


In [11]:
print(D[0])

[ 1.  2.]


In [12]:
print(D[0][0])

1.0


In [13]:
print(D[:, 0])

[ 1.  4.  6.]


In [14]:
print(D.ndim, D.shape)

2 (3, 2)


In [15]:
D[0, 1] = -3
print(D)

[[ 1. -3.]
 [ 4.  5.]
 [ 6.  7.]]


In [16]:
D[0] = -D[2]
print(D)

[[-6. -7.]
 [ 4.  5.]
 [ 6.  7.]]


In [18]:
D = np.array([[1., 2.], [4., 5.], [6., 7.]])
D[0, :] = -D[2, :]
print(D)

[[-6. -7.]
 [ 4.  5.]
 [ 6.  7.]]


In [19]:
E = D # referencje
E[0, 0] = 0
print(E)
print(D)

[[ 0. -7.]
 [ 4.  5.]
 [ 6.  7.]]
[[ 0. -7.]
 [ 4.  5.]
 [ 6.  7.]]


In [20]:
F = D[:, :] # to tez!
F[0, 0] = 3
print(F)
print(D)

[[ 3. -7.]
 [ 4.  5.]
 [ 6.  7.]]
[[ 3. -7.]
 [ 4.  5.]
 [ 6.  7.]]


In [21]:
F[:, :] = D # i to ...
F[0, 0] = 666
print(F)
print(D)

[[ 666.   -7.]
 [   4.    5.]
 [   6.    7.]]
[[ 666.   -7.]
 [   4.    5.]
 [   6.    7.]]


In [22]:
F = np.array(D) # to jest ok
F[0, 0] = 123
print(F)
print(D)

[[ 123.   -7.]
 [   4.    5.]
 [   6.    7.]]
[[ 666.   -7.]
 [   4.    5.]
 [   6.    7.]]


In [23]:
F = np.copy(D) # to tez
F[0, 0] = 11
print(F)
print(D)

[[ 11.  -7.]
 [  4.   5.]
 [  6.   7.]]
[[ 666.   -7.]
 [   4.    5.]
 [   6.    7.]]


In [25]:
G = np.zeros(F.shape)
print(G)
print(F)

G[0] = F[0]
print()
print(G)
print(F)

F[0][0] = 15
print()
print(G)
print(F)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
[[ 11.  -7.]
 [  4.   5.]
 [  6.   7.]]

[[ 11.  -7.]
 [  0.   0.]
 [  0.   0.]]
[[ 11.  -7.]
 [  4.   5.]
 [  6.   7.]]

[[ 11.  -7.]
 [  0.   0.]
 [  0.   0.]]
[[ 15.  -7.]
 [  4.   5.]
 [  6.   7.]]


In [40]:
print(D)
print()
print(D[1:3])
print()
print(D[:, -1])
print()
print(C[3:6])

[[ 666.   -7.]
 [   4.    5.]
 [   6.    7.]]

[[ 4.  5.]
 [ 6.  7.]]

[-7.  5.  7.]

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [41]:
X = np.array(range(100))
print(X.shape, X.ndim)
print(X)

(100,) 1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [42]:
print(X.reshape(20, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


In [43]:
print(X.reshape(10, 10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [44]:
print(X.reshape(13, 3))

ValueError: total size of new array must be unchanged

In [45]:
print(X.reshape(-1, 20))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


In [46]:
print(X.reshape(-1, -1))

ValueError: can only specify one unknown dimension

In [54]:
Y = X.reshape(10, 10)
print(Y)
print(Y.shape, Y.ndim)
print()
print(Y.reshape(1, -1))
print()
print(Y.reshape(1, -1).shape, Y.reshape(1, -1).ndim)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
(10, 10) 2

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
  72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
  96 97 98 99]]

(1, 100) 2


In [52]:
print(Y.ravel())
print(Y.ravel().shape, Y.ravel().ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
(100,) 1


In [55]:
Z = Y[6:10, 1:4]
print(Z)

[[61 62 63]
 [71 72 73]
 [81 82 83]
 [91 92 93]]


In [56]:
print(Z + Z)
print(2 + Z)
print(2 * Z)
print(2./ Z)
print(Z / 2)
print(-Z)
print(Z ** 2)
print(np.sqrt(Z))

[[122 124 126]
 [142 144 146]
 [162 164 166]
 [182 184 186]]
[[63 64 65]
 [73 74 75]
 [83 84 85]
 [93 94 95]]
[[122 124 126]
 [142 144 146]
 [162 164 166]
 [182 184 186]]
[[ 0.03278689  0.03225806  0.03174603]
 [ 0.02816901  0.02777778  0.02739726]
 [ 0.02469136  0.02439024  0.02409639]
 [ 0.02197802  0.02173913  0.02150538]]
[[ 30.5  31.   31.5]
 [ 35.5  36.   36.5]
 [ 40.5  41.   41.5]
 [ 45.5  46.   46.5]]
[[-61 -62 -63]
 [-71 -72 -73]
 [-81 -82 -83]
 [-91 -92 -93]]
[[3721 3844 3969]
 [5041 5184 5329]
 [6561 6724 6889]
 [8281 8464 8649]]
[[ 7.81024968  7.87400787  7.93725393]
 [ 8.42614977  8.48528137  8.54400375]
 [ 9.          9.05538514  9.11043358]
 [ 9.53939201  9.59166305  9.64365076]]


In [57]:
Z = np.array(range(6)).reshape(3, 2)
print(Z)

print(Z * Z)


[[0 1]
 [2 3]
 [4 5]]
[[ 0  1]
 [ 4  9]
 [16 25]]


In [58]:
print(Z.dot(Z))

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [59]:
print(Z.dot(Z.T))

[[ 1  3  5]
 [ 3 13 23]
 [ 5 23 41]]


In [60]:
print(Z.sum(), Z.min(), Z.max(), Z.mean())

15 0 5 2.5


In [61]:
B = np.mat(Z) # B = np.matrix(Z)
print(B * B.T)

[[ 1  3  5]
 [ 3 13 23]
 [ 5 23 41]]


In [62]:
print(Z[0], Z[0].ndim)
print(Z[1], Z[0].ndim)
print()
print(Z[0].dot(Z[1]))
print(np.outer(Z[0], Z[1]))
print()
print(np.mat(Z[0]) * np.mat(Z[1]).T)
print(np.mat(Z[0]).T * np.mat(Z[1]))

[0 1] 1
[2 3] 1

3
[[0 0]
 [2 3]]

[[3]]
[[0 0]
 [2 3]]


In [65]:
print(Z)
print()
print(Z[1])
print()
print(Z + Z[1])

[[0 1]
 [2 3]
 [4 5]]

[2 3]

[[2 4]
 [4 6]
 [6 8]]


In [66]:
print(Z + Z[:, 0])

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [74]:
print(Z[:, 0])

[0 2 4]


In [75]:
print(Z[np.newaxis, :, 0])
print()
print(Z[:, 0, np.newaxis])
print()
print(Z[:, 0][:, np.newaxis])

[[0 2 4]]

[[0]
 [2]
 [4]]

[[0]
 [2]
 [4]]


In [76]:
print(Z)
print()
print(Z + Z[:, 0, np.newaxis])

[[0 1]
 [2 3]
 [4 5]]

[[0 1]
 [4 5]
 [8 9]]


In [77]:
print(np.hstack((Z, Z)))
print(np.concatenate((Z, Z), axis=1))
print()
print(np.vstack((Z, Z)))
print(np.concatenate((Z, Z), axis=0))

[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]]
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]]

[[0 1]
 [2 3]
 [4 5]
 [0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]
 [0 1]
 [2 3]
 [4 5]]


In [78]:
for row in Z:
    print(row, row.shape)
    
for col in Z.T:
    print(col, col.shape)
    

[0 1] (2,)
[2 3] (2,)
[4 5] (2,)
[0 2 4] (3,)
[1 3 5] (3,)


In [79]:
print(dir(Z))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imod__', '__imul__', '__index__', '__init__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__'

In [80]:
print(Z)
print(Z.std(), Z.var(), Z.prod(), Z.trace())
print(Z.argmax())
print(Z.item(Z.argmax()))

[[0 1]
 [2 3]
 [4 5]]
1.70782512766 2.91666666667 0 3
5
5


In [81]:
print(Z.ravel())
print(Z.flatten())

[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [82]:
Z.ravel()[0] = -1
print(Z)
Z.flatten()[0] = 12
print(Z)

[[-1  1]
 [ 2  3]
 [ 4  5]]
[[-1  1]
 [ 2  3]
 [ 4  5]]


### OK, ale po co?

In [83]:
a = np.arange(100)
b = range(100)

In [84]:
a.append(1)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [85]:
from timeit import timeit

print(timeit('np.arange(100000).sum()', setup='import numpy as np', number=1000))
print(timeit('sum(range(100000))', number=1000))

0.12235791661805706
4.75218016279041


In [ ]:
from itertools import imap,starmap,izip
from operator import mul

def d0(v1,v2):
    """                                                                                                     
    d0 is Nominal approach:                                                                                 
    multiply/add in a loop                                                                                  
    """
    out = 0
    for k in range(len(v1)):
        out += v1[k] * v2[k]
    return out

def d1(v1,v2):
    """                                                                                                     
    d1 uses an imap (from itertools)                                                                        
    """
    return sum(imap(mul,v1,v2))

def d2(v1,v2):
    """                                                                                                     
    d2 uses a conventional map                                                                              
    """
    return sum(map(mul,v1,v2))

def d3(v1,v2):
    """                                                                                                     
    d3 uses a starmap (itertools) to apply the mul operator on an izipped (v1,v2)                           
    """
    return sum(starmap(mul,izip(v1,v2)))

def d4(v1,v2):
    return np.dot(v1, v2)

### Bardziej zaawansowane użycie

In [87]:
print(Z)
print(Z > 72)

[[-1  1]
 [ 2  3]
 [ 4  5]]
[[False False]
 [False False]
 [False False]]


In [88]:
print(Z[Z > 72])

[]


In [89]:
Z[Z > 72] = np.array(range(7))
print(Z)

ValueError: NumPy boolean array indexing assignment cannot assign 7 input values to the 0 output values where the mask is true

In [90]:
print(Z[(1, 1)])
print(Z[1, 1])
print(Z[1][1])

3
3
3


In [91]:
print(Z)
print(np.all(Z > -1))
print(np.any(Z > 0))

[[-1  1]
 [ 2  3]
 [ 4  5]]
False
True


In [92]:
X = np.matrix([[1, -1, 0]])
print(X)

[[ 1 -1  0]]


In [93]:
print(X / 0.)
print(X / 0. * -1)

[[ inf -inf  nan]]
[[-inf  inf  nan]]


C:\Python34\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':
C:\Python34\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':
C:\Python34\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: divide by zero encountered in true_divide
  from ipykernel import kernelapp as app
C:\Python34\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: invalid value encountered in true_divide
  from ipykernel import kernelapp as app


In [97]:
Y =  X / 0.
print(Y)
Y[Y == np.inf] = 10000
print(Y)
Y[Y == -np.inf] = -10000
print(Y)
Y[Y == np.NaN] = 0
print(Y)

[[ inf -inf  nan]]
[[ 10000.    -inf     nan]]
[[ 10000. -10000.     nan]]
[[ 10000. -10000.     nan]]


C:\Python34\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':
C:\Python34\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


In [98]:
Y =  X / 0.
print(Y)
Y[Y == np.inf] = 10000
Y[Y == -np.inf] = -10000
# Y[Y is np.NaN] = 0 # To zamieni cala macierz na 0, poniewaz Y is np.NaN zwraca False
Y[np.isnan(Y)] = 0 # poprawne usuniecie nanow
print(Y)

[[ inf -inf  nan]]
[[ 10000. -10000.      0.]]


C:\Python34\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':
C:\Python34\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


In [99]:
print(np.NaN == np.NaN)
print(np.NaN is np.NaN)
print()
print(None == None)
print(None is None)

False
True

True
True


In [100]:
print(Y.dtype)
print(Y)
Z = Y.astype(np.int64) + 600
print()
print(Z.dtype)
print(Z)
Z = Z.astype(np.int8) 
print()
print(Z.dtype)
print(Z)
Z = Z + 0.5
print()
print(Z.dtype)
print(Z)

float64
[[ 10000. -10000.      0.]]

int64
[[10600 -9400   600]]

int8
[[104  72  88]]

float64
[[ 104.5   72.5   88.5]]


In [101]:
print(Z)
print(Z.strides)
print()
print(Z.astype(np.int8))
print(Z.astype(np.int8).strides)
print()
print(Z)
print(Z.T.strides)

[[ 104.5   72.5   88.5]]
(24, 8)

[[104  72  88]]
(3, 1)

[[ 104.5   72.5   88.5]]
(8, 24)


In [102]:
print(Z & Z)

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [103]:
A = Z.astype(np.int8)
B = Z.astype(np.int8)+10
print(A, B)
print(A & B, A ^ B)
print()
C = Z.astype(np.bool)
print(C, -C)
print(C | -C)

[[104  72  88]] [[114  82  98]]
[[96 64 64]] [[26 26 58]]

[[ True  True  True]] [[False False False]]
[[ True  True  True]]


C:\Python34\lib\site-packages\ipykernel\__main__.py:7: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
C:\Python34\lib\site-packages\ipykernel\__main__.py:8: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
